project_id = "qxqvttkcemshgsdobgfe"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.generate-quiz]
    verify_jwt = false
  [functions.send-approval-email]
    verify_jwt = false
  [functions.send-metrics-to-hub]
    verify_jwt = false
